# Generated by Django 4.2.5 on 2023-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textdocument_delete_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TextDocument',
        ),
    ]
