# Generated by Django 4.2.5 on 2023-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_textdocument_delete_summarizationresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='summary',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='profile',
            field=models.ImageField(default='Auth/dummy.jpg', upload_to='Auth/'),
        ),
    ]
